theme = "dot-hugo"
summaryLength = 10
baseURL = "https://demo.gethugothemes.com/dot/site/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false
timeZone = "America/New_York"
title = "Dot"
disableLanguages = []

[build]
writeStats = true
noJSConfigInAssets = false
useResourceCacheWhen = "fallback"

[build.buildStats]
enable = true

[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "style\\.css"

[[build.cachebusters]]
source = "(postcss)\\.config\\.js"
target = "css"

[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"

[[build.cachebusters]]
source = "assets/.*\\.(css|scss|sass)"
target = "css"

[[build.cachebusters]]
source = "data/.*\\.(.*)$"
target = "css"

[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[imaging]
quality = 90

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokai"

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = [ "webmanifest" ]

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "WebAppManifest", "SearchIndex" ]

[services]
[services.disqus]
shortname = "themefisher-template"

[services.googleAnalytics]
ID = "G-MEASUREMENT_ID"

[params]
[params.variables]
body_color = "#f9f9f9"
color_primary = "#02007e"
font_primary = "Lato:wght@300;400;700"
font_primary_type = "sans-serif"
font_scale = "1.17"
font_size = "16px"
text_color = "#636363"
text_dark = "#242738"
text_light = "#f8f9fa"
black = "#000"
white = "#fff"
dark = "#222"
light = "#eee"
font_secondary = ""
font_secondary_type = ""
font_icon = "Font Awesome 6 Free"

[params.plugins]
[[params.plugins.css]]
link = "plugins/themify-icons/icons.css"

[[params.plugins.js]]
link = "js/search.js"

[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"

[[params.plugins.js]]
link = "plugins/glightbox.js"

[[params.plugins.js]]
link = "plugins/youtube-lite.js"

[[params.plugins.js]]
link = "plugins/cookie.js"

[[params.plugins.js]]
link = "plugins/lazy-loader.js"

[[params.plugins.js]]
link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
attributes = "async"

[pagination]
pagerSize = 2

[permalinks]
[permalinks.page]
pages = "/:slugorcontentbasename/"